"""empty message

Revision ID: 4d10f796f704
Revises: 848e0b66f401
Create Date: 2021-10-17 18:54:31.807772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d10f796f704'
down_revision = '848e0b66f401'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('general_txt', 'usr_node',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(length=10),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('general_txt', 'usr_node',
               existing_type=sa.String(length=10),
               type_=sa.BOOLEAN(),
               existing_nullable=True)
    # ### end Alembic commands ###
