"""empty message

Revision ID: 848e0b66f401
Revises: 64b60ee81ed7
Create Date: 2021-10-17 18:19:55.730414

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '848e0b66f401'
down_revision = '64b60ee81ed7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('general_txt', sa.Column('usr_node', sa.Boolean(), nullable=True))
    op.drop_column('general_txt', 'json')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('general_txt', sa.Column('json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('general_txt', 'usr_node')
    # ### end Alembic commands ###
