"""empty message

Revision ID: db251adfecbb
Revises: 7c8d4d4110cc
Create Date: 2021-10-23 18:14:19.780031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db251adfecbb'
down_revision = '7c8d4d4110cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('std_id', sa.Integer(), nullable=True))
    op.drop_column('student', 'student_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('student', 'std_id')
    # ### end Alembic commands ###
